#! /bin/sh

sxhkd &
feh --randomize --bg-fill ~/Pictures/Wallpapers/* &
pulseeffects --gapplication-service &
picom &
$HOME/.config/polybar/launch.sh & 
$HOME/.config/scripts/capslock_ctrl_esc_modifier.sh &
wmname LG3D &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true

# Colors
# shellcheck source=/dev/null
. "$HOME/.local/share/themes/colorschemes/bspwm.cfg"
bspc config focused_border_color            "$focusedbordercolor"
bspc config active_border_color             "$activebordercolor"
bspc config normal_border_color             "$normalbordercolor"
bspc config urgent_border_color             "$urgentbordercolor"
bspc config presel_feedback_color           "$preselfeedbackcolor"

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a jetbrains-studio desktop='^4' follow=on
bspc config external_rules_command $HOME/.scripts/android_emulator_rule.sh
#bspc config external_rules_command $HOME/.scripts/emulator_rule.sh
